services:
  - type: web
    name: trello-telegram-bot-v3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class=gthread --threads=2 --bind=0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: TRELLO_KEY
        sync: false
      - key: TRELLO_TOKEN
        sync: false
      - key: BOARD_ID
        sync: false
